services:
  vrising:
    image: zkoesters/vrising:latest
    restart: unless-stopped # Required for the restarts to work
    stop_grace_period: 15s # Might need to increase with longer saves
    ports:
      - "9876:9876/udp"
      - "9877:9877/udp"
    environment:
      TZ: "America/Los_Angeles"
      PUID: 1001
      PGID: 1001
      VR_NAME: "V Rising Docker Server"
      VR_DESCRIPTION: "V Rising server hosted on Docker"
      VR_RCON_ENABLED: true
      VR_RCON_PASSWORD: "rconPassword"
      VR_RCON_PORT: 25575
      VR_GAME_PORT: 9876
      VR_QUERY_PORT: 9877
      VR_LIST_ON_EOS: true
      VR_LIST_ON_STEAM: true
      VR_SAVE_NAME: "dockerWorld"
    volumes:
      - ./awesome-vrising-server/server:/vrising/server
      - ./awesome-vrising-server/data:/vrising/data
      - ./awesome-vrising-server/announce:/vrising/announce # Only needed if you are using Auto Announce
