name: Tests
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  test:
    name: Image Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run tests
        run: make test
